export const LABS_DESCRIPTION = 'Run small AI models in your browser for free. Try Qwen3, MiniCPM5 and Qwen3.5 in local chat, a detective game and decision experiments. No account or API key.';

export const LABS_FAQ = Object.freeze([
  { question: 'Can I run an LLM locally in a web browser?', answer: 'Yes. LocalClaw Labs downloads a small language model into browser storage after you click Load model. The wllama engine runs inference on your device using WebAssembly and WebGPU when available, with a CPU path for smaller models. No hosted AI API is used for your prompts.' },
  { question: 'Which models can I try in LocalClaw Labs?', answer: 'There are five presets: Qwen3 0.6B Q4_K_M (397 MB), Qwen3 1.7B Q4_K_M (1.11 GB), Qwen3 0.6B Q8_0 (639 MB), MiniCPM5 2B Q4_K_M (1.56 GB) and Qwen3.5 4B Q4_K_M (3.01 GB). The last three are the presets used by SemIf, formerly OpenJEV. These are rounded download sizes, not total memory requirements.' },
  { question: 'Is the browser AI playground free?', answer: 'Yes. All four Labs experiments are free and require no account, API key or paid LocalClaw desktop license. You supply the device, electricity, browser storage and network connection for downloading the model.' },
  { question: 'Are my prompts sent to a server?', answer: 'Labs does not send prompts or model answers to an AI service and does not run session recordings. Conversations are held in this tab and disappear on reload. LocalClaw and the model host still receive normal network requests when delivering the page, runtime and model files. Downloaded weights can remain in browser storage until removed or evicted.' },
  { question: 'What do WebGPU and WebAssembly do?', answer: 'WebAssembly runs the local inference engine inside the browser. WebGPU lets a compatible browser use your graphics processor. Smaller Labs models can fall back to the CPU; the 4B preset requires WebGPU here. Actual speed depends on your browser, hardware, free memory and input length.' },
  { question: 'What does RLCD mean, and is this Jev?', answer: 'RLCD means Reinforcement Learning for Calibrated Decisions, a training objective described by TypeSafe. The Decisions / RLCD tab is an educational experiment with standard open models, not Jev and not verified RLCD-trained weights. Its option scores and generated JSON do not establish calibrated confidence. LocalClaw is independent of TypeSafe and SemIf.' },
  { question: 'How does the decision comparison work?', answer: 'You provide a situation, a question and two to six options. The model first scores allowed letter choices using one constrained output token. It then writes its own estimates as unconstrained JSON. Labs shows real timings, checks the JSON format and keeps invalid output visible. Warm-up is excluded, scores run first, and prompt caching is disabled for the measured calls. This is not a benchmark against Jev.' },
  { question: 'Can I try a new situation without downloading a model?', answer: 'Yes. Shuffle situation fills in a new fictional situation, question and set of options from 18 authored examples. Choose All situations, Support ticket, Email check or Detective Crab. Shuffling does not call an AI service or start a download. Load a model and click Compare methods only when you want an actual model result.' },
  { question: 'Does Labs work on mobile or offline?', answer: 'Mobile support depends on the browser and available memory; start with Qwen3 0.6B Q4. The 4B preset is intended for a computer with WebGPU and about 6 GB of free memory. After loading, inference does not need an AI server, but offline page reloads are not guaranteed and browsers may evict cached files. Keep the tab open and online for setup.' },
  { question: 'How do I remove a downloaded model?', answer: 'Unload model releases the active model from memory while keeping its downloaded weights cached. Under How local inference works, Remove downloaded models deletes the listed Labs model files from this site\'s browser storage. Loading one again will download it again.' },
]);
