export const LABS_DESCRIPTION = 'Run small AI models in your browser for free. Try Qwen3, MiniCPM5 and Qwen3.5 in local chat, a detective game and decision experiments. No account or API key.';

export const LABS_FAQ = Object.freeze([
  { question: 'Can I run an LLM locally in a web browser?', answer: 'Yes. LocalClaw Labs downloads a small language model into browser storage after you click Load model. The wllama engine runs inference on your device using WebAssembly and WebGPU when available, with a CPU path for smaller models. No hosted AI API is used for your prompts.' },
  { question: 'Which models can I try in LocalClaw Labs?', answer: 'There are five presets: Qwen3 0.6B Q4_K_M (397 MB), Qwen3 1.7B Q4_K_M (1.11 GB), Qwen3 0.6B Q8_0 (639 MB), MiniCPM5 2B Q4_K_M (1.56 GB) and Qwen3.5 4B Q4_K_M (3.01 GB). The last three are the presets used by SemIf, formerly OpenJEV. These are rounded download sizes, not total memory requirements.' },
  { question: 'Is the browser AI playground free?', answer: 'Yes. All four Labs experiments are free and require no account, API key or paid LocalClaw desktop license. You supply the device, electricity, browser storage and network connection for downloading the model.' },
  { question: 'Are my prompts sent to a server?', answer: 'Labs does not send prompts or model answers to an AI service and does not run session recordings. Conversations are held in this tab and disappear on reload. LocalClaw and the model host still receive normal network requests when delivering the page, runtime and model files. Downloaded weights can remain in browser storage until removed or evicted.' },
  { question: 'What do WebGPU and WebAssembly do?', answer: 'WebAssembly runs the local inference engine inside the browser. WebGPU lets a compatible browser use your graphics processor. Smaller Labs models can fall back to the CPU; the 4B preset requires WebGPU here. Actual speed depends on your browser, hardware, free memory and input length.' },
  { question: 'What does RLCD mean, and is this Jev?', answer: 'RLCD means Reinforcement Learning for Calibrated Decisions, a training objective described by TypeSafe. The Decisions / RLCD tab is an educational experiment with standard open models, not Jev and not verified RLCD-trained weights. Its option scores and generated JSON do not establish calibrated confidence. LocalClaw is independent of TypeSafe and SemIf.' },
  { question: 'What is the difference between Noul, Score and Choice?', answer: 'Noul asks a yes/no question and displays the local model’s estimated probability of Yes, from 0 to 1. Score uses an ordered rubric of two to six levels and computes the probability-weighted level index, starting at zero. Choice uses two to six unordered options and displays the leading option and the distribution. These are educational local-model adaptations of TypeSafe’s question shapes, not Jev API responses or calibrated estimates. A Noul value near 0.5 means uncertainty, not half-true; a Score can fall between levels.' },
  { question: 'How does the decision comparison work?', answer: 'Choose Noul, Score or Choice, then provide a situation, question and the matching criteria. Noul uses fixed Yes/No outcomes; Score and Choice accept two to six levels or options. The model first scores allowed letters using one constrained output token. Labs derives typed data from that distribution. A second call writes its own distribution as raw JSON, which is validated and shown unchanged. Timings are real, warm-up is excluded, and prompt caching is disabled for measured calls. No calibrated confidence field is claimed. This is not a Jev benchmark.' },
  { question: 'Can I try a new situation without downloading a model?', answer: 'Yes. There are 54 authored fictional examples: 18 Noul, 18 Score and 18 Choice. Choose a type, optionally filter by Support ticket, Email check or Detective Crab, then pick an example from the list or use Shuffle situation. Shuffling avoids immediate repeats and cycles through the selected pool. Neither browsing nor shuffling loads a model or creates results. Click Load model and Compare methods for a real local run.' },
  { question: 'Does Labs work on mobile or offline?', answer: 'Mobile support depends on the browser and available memory; start with Qwen3 0.6B Q4. The 4B preset is intended for a computer with WebGPU and about 6 GB of free memory. After loading, inference does not need an AI server, but offline page reloads are not guaranteed and browsers may evict cached files. Keep the tab open and online for setup.' },
  { question: 'How do I remove a downloaded model?', answer: 'Unload model releases the active model from memory while keeping its downloaded weights cached. Under How local inference works, Remove downloaded models deletes the listed Labs model files from this site\'s browser storage. Loading one again will download it again.' },
]);
